FROM bitnami/nginx:latest

COPY config/nginx.conf /opt/bitnami/nginx/conf/nginx.conf

# Fix permissions
USER root
RUN chmod -R g+rwX /opt/bitnami/nginx/

# Switch back to default bitnami nginx user
USER 1001
