name: CI Workflow
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write

    env:
      RAILS_ENV: test
      RACK_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1/disclosure-checker-test"
      EXTERNAL_URL: mocked_in_tests
      DEV_TOOLS_ENABLED: "1"

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: disclosure-checker-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        run: bin/rails db:prepare

      - name: Run linters and tests
        run: bundle exec rake

      - name: Code coverage
        uses: joshmfrankel/simplecov-check-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_suite_coverage: 100
          minimum_file_coverage: 100

  snyk-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/ruby@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  build-and-deploy:
    needs: [test, snyk-security]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
